### ISSUE TITLE
Windows version in v0.2.0 not recognizing switch

### ISSUE THREAD

**Issue by aerospraymg** [Victrid/splatplost#52] opened 2022-10-19 23:40 UTC
Hello!
I don't use Github but I made an account because I can't figure out how to use the Windows version of Splatplost. I tried both using the USB-C and remote connections, but neither will recognize my Switch. If it matters, I'm on Windows 10 and trying to connect to Splatoon 3. 
USB-C connection: 
![image](https://user-images.githubusercontent.com/116231452/196824025-f3794fcd-f78f-4a62-91b6-e004418fa64e.png) My computer recognizes my Switch via Bluetooth, but the program itself doesn't. I've tried reconnecting it and closing the program, but nothing seems to work. 
For the remote connection, I'm unsure of what to put in the remote server box. I went to the Switch pairing menu, but no new controllers appeared. 
![image](https://user-images.githubusercontent.com/116231452/196824292-fcb78122-8de4-4154-9a8b-7a355a5a73bc.png)
I don't have Linux, or any knowledge of Python, so any help is appreciated! This is a great tool and I've seen so many printed pictures in the plaza.

**Comment by Alenonimo** [comment] 2022-10-25 11:02
The SerialException error I got a few times. Seems like there's a copy of the program open somewhere. Restarting the computer will solve that, at the very least.

Still, my issue is that connecting the Switch to the PC with a USB cable and pressing "Start Pairing" will give no response whatsoever. Last time I tried, I was using Windows 10. I also don't know how to install the 0.2.0 version on my Linux machine.

**Comment by Victrid** [comment] 2022-10-28 03:00
Hello,

I’m still working on the Windows version. The documentation and guides for windows using will be updated recently.

However, connecting switch with the USB cable directly to a windows machine is a no-go, so be the windows machine with bluetooth connection. This is determined by USB protocol and windows bluetooth driver strategy.

The “Splatplost USB” option here is a dedicated hardware to connect to Switch and currently under development, which is a USB serial device which will translate the serial commands to emulate a switch controller (that is why it raises serial error), while the “Remote” one is used to connect to other common linux hardware, headless but bluetooth enabled, like a Raspberry Pi.

The windows version requires to recompile every driver for possible bluetooth adapters (this is caused by windows driver policies, which is different with Linux), while most of them are proprietary owned. You may need to check the `flashable image` option, to boot your computer into a out-of-the-box linux version.

Since this issue is caused by misunderstanding and can’t be fixed, I’ll close this issue. If you have further general questions, please comment them in the issue #13 (general version 0.2.x pre release discussions), otherwise, you may reopen this issue.

**Closed as completed by Victrid** 2022-10-28 03:00 UTC
